version: 2.1
# todo:
# - replicate travis + appveyour features in circle
# - add notarisation signing for win/mac on circle
# - consider writing a custom orb
# - rebase all the circle stuff and squash
# - add caching

orbs:
# see https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7.0
jobs:
  compile:
  # todo switch to evolvedbinary/fs-build:centos7_x64-be
    executor:
      name: node/default
      tag: '14.17.5'
    steps:
      - checkout
      - run: sudo apt-get --yes install libx11-dev libxkbfile-dev
      - node/install:
          install-yarn: true          
      - node/install-packages:
        # TODO: check if this is what we realy realy want
          override-ci-command: yarn install --ignore-engines
          pkg-manager: yarn
      - run: node --version
      - run: yarn --version
      - run: yarn build
workflows:
  run-npm-command:
    jobs:
      - compile
      # - node/run:
      #     setup: apt-get --yes install libx11-dev libxkbfile-dev     
      #     pkg-manager: yarn
      #     override-ci-command: yarn install --ignore-engines
      #     yarn-run: yarn build
      #     version: '14.17.5'