version: 2.1
# todo:
# - add notarisation signing for win/mac on circle (post-step)
# - squash circle commits
# - add context for secrets 
# - contact support about windows orb fail

orbs:
# see https://circleci.com/developer/orbs/orb/circleci/node
# see https://circleci.com/developer/orbs/orb/circleci/windows
  node: circleci/node@4.7.0
  win: circleci/windows@2.4.1
executors:
  linux: &nix
    docker:
      - image: cimg/python:3.9.6-node
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD
  windows: win/default
  macos: # macos executor using xcode 11 should it be 12?
    macos:
      xcode: 12.5.1

jobs:
  compile:
    parameters:
        os:
          type: executor
        node-version:
          type: string
    executor: << parameters.os >>      
    steps:
      - checkout
      - when:
          condition: 
            equal: [<<parameters.os>>, *nix]
          steps:
            - run: 
                command: |
                    sudo apt-get update
                    sudo apt-get install -y libx11-dev libxkbfile-dev libsecret-1-0   
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
          install-npm: false          
      - node/install-packages:
          cache-path: ~/project/node_modules
        # TODO: check if this is what we want, what we really really want
          override-ci-command: yarn install --ignore-engines
          pkg-manager: yarn
      - run: node --version
      - run: yarn --version
      - run: yarn build
workflows:
  compile-all:
    jobs:
      - compile:
          matrix:
            parameters:
              os: [linux, windows, macos]
              node-version: ["12.22.5", "14.17.5"]